
[[tools]]
name = "bifrost"
path = "tools/Bifrost"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_READS> <INPUT_FILES_SEQUENCES> -o <OUTPUT_FILE> --verbose --fasta"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
# suggested-memory-prefix = "-m"

[[tools]]
name = "cuttlefish2-ref"
path = "tools/cuttlefish"
arguments = "build --ref -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"

[[tools]]
name = "cuttlefish2-reads"
path = "tools/cuttlefish"
arguments = "build --read -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"


[[tools]]
name = "bcalm"
path = "tools/bcalm"
arguments = "-in <INPUT_FILES_LIST> -kmer-size <KVALUE> -nb-cores <THREADS> -abundance-min <MULTIPLICITY> -out-tmp <TEMP_DIR> -out <OUTPUT_FILE>"

[[tools]]
name = "biloki"
path = "tools/biloki"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE>"

# [[tools]]
# name = "biloki-links"
# path = "tools/biloki-links"
# arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE>"

[[tools]]
name = "biloki-ram"
path = "tools/biloki"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE> --prefer-memory"


[[datasets]]
name = "gut"
lists = ["datasets/lists/gut.in"]


# [[datasets]]
# name = "chr14"
# files = [
#     "datasets/Chr14/frag_1.fastq.gz",
#     "datasets/Chr14/frag_2.fastq.gz",
# ]

[[datasets]]
name = "salmonella-1k"
tar = "datasets/salmonella-strains.tar"
limit = 1000

[[datasets]]
name = "salmonella-10k"
tar = "datasets/salmonella-strains.tar"
limit = 10000

[[datasets]]
name = "salmonella-100k"
tar = "datasets/salmonella-strains.tar"
limit = 100000

[[datasets]]
name = "salmonella-all"
tar = "datasets/salmonella-strains.tar"

[[datasets]]
name = "father"
lists = ["datasets/lists/father.in"]

[[datasets]]
name = "mother"
lists = ["datasets/lists/mother.in"]

[[datasets]]
name = "human-dbjs"
files = [
    "datasets/human-dbjs/father.fa",
    "datasets/human-dbjs/mother.fa",
]

[[datasets]]
name = "mtest"
files = ["datasets/human-giab/mother/D3_S1_L001_R1_001.fastq.gz"]

[[working-dirs]]
name = "ram"
path = "working-dirs/ram/benchmark-workdir"

[[working-dirs]]
name = "hdd"
path = "working-dirs/hdd/benchmark-workdir"

[[working-dirs]]
name = "ssd"
path = "working-dirs/ssd/benchmark-workdir"

[[working-dirs]]
name = "vakka"
path = "working-dirs/vakka/benchmark-workdir"


[[benchmarks]]
name = "mtest"
datasets = ["mtest"]
tools = ["biloki"] # , "biloki-links"]
working-dirs = ["hdd"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [12]
max-memory = 256
min-multiplicity = 2
size-check-time = 500

[[benchmarks]]
name = "gut"
datasets = ["gut"]
tools = ["cuttlefish2-reads", "bcalm", "biloki"] # , "biloki-links"]
working-dirs = ["ram", "vakka", "ssd", "hdd"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [32]
max-memory = 256
min-multiplicity = 2
size-check-time = 500

[[benchmarks]]
name = "human"
datasets = ["father", "mother"]
tools = ["cuttlefish2-reads", "bcalm", "biloki"] # , "biloki-links"]
working-dirs = ["ram", "vakka", "ssd", "hdd"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [32]
max-memory = 256
min-multiplicity = 2
size-check-time = 750


[[benchmarks]]
name = "human-reassemble"
datasets = ["human-dbjs"]
tools = ["cuttlefish2-ref", "bcalm", "biloki"] # , "biloki-links"]
working-dirs = ["ram", "vakka", "ssd", "hdd"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [32]
max-memory = 256
min-multiplicity = 1
size-check-time = 750

# [[benchmarks]]
# name = "chromosome-14"
# datasets = ["chr14"]
# tools = ["biloki", "biloki-links, "cuttlefish2-reads"] # "bcalm"] # , "bifrost"]
# working-dirs = ["ram", "vakka", " "ssdh,dd"]
# copy-dataset = true
# trim-before = true
# kvalues = [3, 5, 7, 15, 23, 31, 63]
# threads = [16]
# max-memory = 64
# min-multiplicity = 2
# size-check-time = 500

 [[benchmarks]]
 name = "salmonella-small"
 datasets = ["salmonella-1k", "salmonella-10k", "salmonella-100k"]
 tools = ["biloki", "biloki-links", "bcalm", "cuttlefish2-ref"]
 working-dirs = ["ram", "vakka", "ssd", "hdd"]
 copy-dataset = true
 trim-before = true
 kvalues = [15, 31, 63]
 threads = [32]
 max-memory = 256
 min-multiplicity = 1
 size-check-time = 1000

[[benchmarks]]
name = "salmonella-big"
datasets = ["salmonella-100k", "salmonella-all"]
tools = ["biloki", "biloki-links", "cuttlefish2-ref"]
working-dirs = ["vakka", "hdd"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [32]
max-memory = 256
min-multiplicity = 1
size-check-time = 1000
