
[[tools]]
name = "bifrost"
path = "tools/Bifrost"
arguments = "build -k <KVALUE> -t <THREADS>  <INPUT_FILES_READS> <INPUT_FILES_SEQUENCES> -o <OUTPUT_FILE> --verbose --fasta"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"
# suggested-memory-prefix = "-m"

[[tools]]
name = "cuttlefish2-ref"
path = "tools/cuttlefish"
arguments = "build --ref -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"

[[tools]]
name = "cuttlefish2-reads"
path = "tools/cuttlefish"
arguments = "build --read -l <INPUT_FILES_LIST> -k <KVALUE> -c <MULTIPLICITY> -t <THREADS> -o <OUTPUT_FILE>  -w <TEMP_DIR>"
reads-arg-prefix = "-r"
sequences-arg-prefix = "-s"


[[tools]]
name = "bcalm"
path = "tools/bcalm"
arguments = "-in <INPUT_FILES_LIST> -kmer-size <KVALUE> -nb-cores <THREADS> -abundance-min <MULTIPLICITY> -out-tmp <TEMP_DIR> -out <OUTPUT_FILE>"

[[tools]]
name = "biloki"
path = "tools/BiLoki"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE>"


[[tools]]
name = "biloki-ram"
path = "tools/BiLoki"
arguments = "build -k <KVALUE> -j <THREADS> -s <MULTIPLICITY> -l <INPUT_FILES_LIST> -t <TEMP_DIR> -o <OUTPUT_FILE> --prefer-memory"


[[datasets]]
name = "gut"
lists = ["datasets/lists/gut.in"]


[[datasets]]
name = "chr14"
files = [
    "datasets/Chr14/frag_1.fastq.gz",
    "datasets/Chr14/frag_2.fastq.gz",
]

[[datasets]]
name = "salmonella-1k"
lists = ["datasets/lists/salmonella-1k.in"]

[[datasets]]
name = "father"
lists = ["/tmp/father-list.in"]

[[working-dirs]]
name = "ram"
path = "/tmp/benchmark-workdir"

[[benchmarks]]
name = "human"
datasets = ["father"]
tools = ["cuttlefish2-reads", "biloki"]
working-dirs = ["ram"]
copy-dataset = true
trim-before = true
kvalues = [15, 63, 31]
threads = [128]
max-memory = 64
min-multiplicity = 2
size-check-time = 500


[[benchmarks]]
name = "gut"
datasets = ["gut"]
tools = ["cuttlefish2-reads", "biloki", "bcalm"]
working-dirs = ["ram"]
copy-dataset = true
trim-before = true
kvalues = [15, 63, 31]
threads = [16]
max-memory = 64
min-multiplicity = 2
size-check-time = 500

[[benchmarks]]
name = "chromosome-14"
datasets = ["chr14"]
tools = ["biloki", "cuttlefish2-reads", "bcalm"] # , "bifrost"]
working-dirs = ["ram"]
copy-dataset = true
trim-before = true
kvalues = [3, 5, 7, 15, 23, 31, 63]
threads = [16]
max-memory = 64
min-multiplicity = 2
size-check-time = 500

[[benchmarks]]
name = "salmonella-1k"
datasets = ["salmonella-1k"]
tools = ["biloki", "cuttlefish2-ref", "bcalm"] # , "bifrost"]
working-dirs = ["ram"]
copy-dataset = true
trim-before = true
kvalues = [15, 31, 63]
threads = [16]
max-memory = 64
min-multiplicity = 1
size-check-time = 500

[[benchmarks]]
name = "test1"
datasets = ["chr14"]
tools = ["cuttlefish2-reads", "biloki", "bifrost"]
working-dirs = ["ram"]
copy-dataset = true
trim-before = true
kvalues = [31, 63]
threads = [16]
max-memory = 8
min-multiplicity = 2
size-check-time = 500
