
[[datasets]]
name = "salmonella-10"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 10

[[datasets]]
name = "salmonella-1k"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 1000

[[datasets]]
name = "salmonella-5k"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 5000

[[datasets]]
name = "salmonella-10k"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 10000

[[datasets]]
name = "salmonella-50k"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 50000

[[datasets]]
name = "salmonella-100k"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true
limit = 100000

[[datasets]]
name = "salmonella-all"
tar = "/abga/work/acracco/ggcat-test/datasets/salmonella-strains.tar"
copy-dataset = true

[[datasets]]
name = "father"
lists = ["/abga/work/acracco/ggcat-test/datasets/lists/father.in"]

[[datasets]]
name = "mother"
lists = ["/abga/work/acracco/ggcat-test/datasets/lists/mother.in"]

# [[datasets]]
# name = "human-dbjs"
# files = [
#     "/abga/work/acracco/ggcat-test/datasets/human-dbjs/father.fa",
#     "/abga/work/acracco/ggcat-test/datasets/human-dbjs/mother.fa",
# ]


[[datasets]]
name = "gut"
lists = ["/abga/work/acracco/ggcat-test/datasets/lists/gut.in"]


# [[working-dirs]]
# name = "ram"
# path = "../working-dirs/ram/benchmark-workdir"

# [[working-dirs]]
# name = "hdd"
# path = "../working-dirs/hdd/benchmark-workdir"

[[working-dirs]]
name = "ssd"
path = "/abga/work/acracco/ggcat-test/benchmark-workdir"

# [[working-dirs]]
# name = "vakka"
# path = "../working-dirs/vakka/benchmark-workdir"
