[[datasets]]
name = "salmonella-10"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-1k.in"]
limit = 10

[[datasets]]
name = "salmonella-100"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-1k.in"]
limit = 100

[[datasets]]
name = "salmonella-1k"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-1k.in"]

[[datasets]]
name = "salmonella-5k"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-5k.in"]

[[datasets]]
name = "salmonella-10k"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-10k.in"]

[[datasets]]
name = "salmonella-50k"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-50k.in"]

[[datasets]]
name = "salmonella-100k"
lists = ["/home/andrea/genome-assembly/data/lists/salmonella-50k.in"]

[[datasets]]
name = "salmonella-all"
tar = "../datasets/salmonella-strains.tar"

[[datasets]]
name = "father"
lists = ["../datasets/lists/father.in"]

[[datasets]]
name = "mother"
lists = ["../datasets/lists/mother.in"]

[[datasets]]
name = "human-dbjs"
files = [
    "../datasets/human-dbjs/father.fa",
    "../datasets/human-dbjs/mother.fa",
]

[[datasets]]
name = "mtest"
files = ["../datasets/human-giab/mother/D3_S1_L001_R1_001.fastq.gz"]


[[datasets]]
name = "gut"
lists = ["../datasets/lists/gut.in"]


[[working-dirs]]
name = "ram"
path = "../working-dirs/ram/benchmark-workdir"

[[working-dirs]]
name = "hdd"
path = "../working-dirs/hdd/benchmark-workdir"

[[working-dirs]]
name = "ssd"
path = "../working-dirs/ssd/benchmark-workdir"

[[working-dirs]]
name = "vakka"
path = "../working-dirs/vakka/benchmark-workdir"
